#!/usr/bin/env python
# -*- coding: utf-8 -*-
# 22/12/2025
# Author: Sadettin Y. Ugurlu



"""
Gereken paketler:
pip install scikit-learn tensorflow pandas numpy
"""

import random
import warnings
import numpy as np
import pandas as pd

from sklearn.model_selection import KFold
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import r2_score, mean_absolute_error

import tensorflow as tf
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense, Dropout, LeakyReLU
from tensorflow.keras.callbacks import EarlyStopping

warnings.filterwarnings("ignore")

# =======================================================
# 0. Reproducibility
# =======================================================
SEED = 42
random.seed(SEED)
np.random.seed(SEED)
tf.random.set_seed(SEED)

# =======================================================
# 1. Konfigürasyon
# =======================================================
train_csv_path = "train_ready.csv"
test_csv_path  = "test_ready.csv"

target_col = "Dielectric constant(εrel)"
drop_cols = ["Name", "Formula", "Dielectric constant(εrel)", "nD", "SMILES"]

# ANN hyperparams
EPOCHS = 125
BATCH_SIZE = 64
PATIENCE = 30
VERBOSE_FIT = 0

# =======================================================
# 2. Feature list (SENİN LİSTEN)
# =======================================================
all_features = [
    "AATSC0s",
    "MINssNH",
    "MACCS_FP_117",
    "MAXssNH",
    "MACCS_FP_137",
    "nHRing",
    "BCUTs-1h",
    "MACCS_FP_161",
    "AATS0s",
    "BIC0",
    "LogP",
    "SLogP",
    "HBD",
    "nHBDon",
    "ETA_dEpsilon_D",
    "MACCS_FP_148",
    "SIC0",
    "MACCS_FP_151",
    "n5AHRing",
    "AMID_N",
    "IC0",
    "MACCS_FP_131",
    "TopoPSA(NO)",
    "TPSA",
    "MTPSA",
    "MACCS_FP_122",
    "TPSA1",
    "AETA_eta_L",
    "AMID_O",
    "VSA_EState3",
    "TopoPSA",
    "MACCS_FP_134",
    "MAXaaN",
    "VSAEstate2",
    "MACCS_FP_41",
    "VMcGowan",
    "Vabc",
    "Xp-0dv",
    "AETA_eta",
    "MINaaN",
    "PEOEVSA5",
    "MACCS_FP_123",
    "Sp",
    "nN",
    "GATS1se",
    "MACCS_FP_164",
    "PEOE_VSA6",
    "ETA_eta_L",
    "MID_N",
    "apol",
    "AATSC1dv",
    "NsOH",
    "SMR_VSA2",
    "MATS1dv",
    "MACCS_FP_152",
    "MACCS_FP_127",
    "MRVSA1",
    "CIC0",
    "MINdS",
    "MAXsNH2",
    "AATSC1c",
    "ATSC0s",
    "MACCS_FP_143",
    "MAXdS",
    "MATS3s",
    "StN",
    "n5HRing",
    "BIC1",
    "RPCG",
    "GATS5m",
    "NtN",
    "SsOH",
    "LabuteASA.1",
    "MINsNH2",
    "ETA_dEpsilon_C",
    "ETA_eta",
    "LabuteASA",
    "MACCS_FP_83",
    "n5ARing",
    "AATSC3s",
    "ETA_alpha",
    "GATS5Z",
    "GATS5s",
    "AATSC0dv",
    "GATS1c",
    "ATS0v",
    "ATSC1dv",
    "MATS6d",
    "BCUTp-1l",
    "GATS1pe",
    "ETA_epsilon_4",
    "SpMAD_Dzi",
    "MACCS_FP_73",
    "SpMAD_Dzp",
    "GATS1are",
    "MACCS_FP_78",
    "AMID_h",
    "RNCG",
    "SpMAD_Dzare",
    "SpMAD_Dzse",
    "slogPVSA11",
    "AATS4s",
    "MID_h",
    "MACCS_FP_121",
    "SMR_VSA3",
    "SZ",
    "MACCS_FP_156",
    "AATS3s",
    "MACCS_FP_47",
    "PEOE_VSA4",
    "AATSC3se",
    "MATS1Z",
    "SpMAD_Dzpe",
    "PEOE_VSA1",
    "MRVSA2",
    "BCUTse-1h",
    "MACCS_FP_107",
    "MDEN-12",
    "PEOEVSA0",
    "MATS1m",
    "AATSC1Z",
    "AETA_beta",
    "AATSC2c",
    "MID_O",
    "MATS3se",
    "GATS1Z",
    "BCUTdv-1h",
    "GATS1m",
    "SpMAD_Dzv",
    "ZMIC1",
    "MAXdsCH",
    "ATS0p",
    "ZMIC3",
    "PEOEVSA3",
    "SRW09",
    "nO",
    "BCUTpe-1h",
    "GATS1s",
    "BCUTd-1l",
    "MATS1p",
    "ATS4i",
    "SM1_Dzse",
    "BCUTc-1h",
    "ETA_dPsi_A",
    "AATSC3c",
    "AATS1p",
    "AATSC0are",
    "BCUTare-1h",
    "AATSC0pe",
    "AATSC5d",
    "AATSC1are",
    "VR2_DzZ",
    "SlogP_VSA1",
    "MAXtsC",
    "NsssN",
    "SMR",
    "VR2_Dzp",
    "MINdssC",
    "AATS1se",
    "AETA_eta_RL",
    "MINtsC",
    "SpDiam_A",
    "ZMIC2",
    "AATS4dv",
    "Xch-6d",
    "AATS2d",
    "AATS7dv",
    "AATSC0se",
    "AETA_beta_ns",
    "MACCS_FP_106",
    "SM1_Dzpe",
    "AATSC1m",
    "ETA_epsilon_2",
    "AATS1are",
    "ETA_epsilon_5",
    "SM1_Dzm",
    "SM1_DzZ",
    "MATS5dv",
    "MATS6s",
    "SpMax_A",
    "MACCS_FP_57",
    "AATS3dv",
    "AATSC4s",
    "ZMIC0",
    "HBA",
    "NaaN",
    "VR2_Dzm",
    "ATS4s",
    "ETA_dBeta",
    "SRW07",
    "NdsN",
    "ETA_eta_F",
    "AETA_dBeta",
    "ATS5i",
    "AATSC6s",
    "TSRW10",
    "Xp-1dv",
    "nH",
    "AATS0se",
    "ATS0i",
    "EstateVSA9",
    "BCUTc-1l",
    "BCUTdv-1l",
    "VR2_Dzse",
    "nX",
    "MATS1s",
    "Xch-7d",
    "piPC3",
    "GATS2c",
    "AETA_beta_s",
    "AATSC3pe",
    "NdssSe",
    "AATS1pe",
    "MACCS_FP_130",
    "C1SP2",
    "MAXaasC",
    "SpMAD_A",
    "VE3_Dzm",
    "AXp-0dv",
    "ETA_dAlpha_B",
    "ATS2p",
    "Mse",
    "MIC0",
    "SdsN",
    "VR2_Dzi",
    "AATS3p",
    "MATS5d",
    "ATSC1s",
    "AMID",
    "SdssSe",
    "VR2_Dzare",
    "slogPVSA0",
    "ATSC1p",
    "AATSC0i",
    "VR2_Dzv",
    "ATSC0v",
    "MACCS_FP_126",
    "SsssN",
    "EState_VSA10",
    "BCUTZ-1h",
    "AATSC5dv",
    "BIC3",
    "AATSC1pe",
    "AATSC1se",
    "VE3_Dzp",
    "ZMIC5",
    "MINaasC",
    "VE3_Dzv",
    "nAHRing",
    "LogEE_A",
    "BCUTv-1h",
    "nHBAcc",
    "ATS1s",
    "ETA_psi_1",
    "GATS1dv",
    "MACCS_FP_154",
    "LogEE_Dzp",
    "MRVSA9",
    "AATSC6d",
    "ETA_epsilon_3",
    "AETA_alpha",
    "VSAEstate9",
    "VE1_Dzare",
    "ATS5se",
    "AATS3v",
    "ATS1p",
    "PEOE_VSA10",
    "AATSC6i",
    "CIC3",
    "MATS5Z",
    "BCUTp-1h",
    "Xp-2dv",
    "MATS6i",
    "EstateVSA8",
    "AATSC1v",
    "MATS5m",
    "MINdsCH",
    "ATSC3d",
    "VE3_Dzi",
    "AATSC1p",
    "SM1_Dzi",
    "AATSC5pe",
    "BCUTm-1h",
    "MACCS_FP_89",
    "MATS5s",
    "MATS1i",
    "MAXdssC",
    "slogPVSA1",
    "Sv",
    "AATSC0c",
    "SpAD_Dzp",
    "GATS1p",
    "AATS2i",
    "ATS4se",
    "ATS5pe",
    "SpMax_Dzp",
    "SIC2",
    "ATSC1se",
    "BCUTi-1h",
    "BCUTd-1h",
    "ATSC0se",
    "NdO",
    "AETA_eta_FL",
    "MINtN",
    "VE3_Dzpe",
    "ATSC0c",
    "VE3_Dzse",
    "SIC3",
    "MACCS_FP_124",
    "ETA_dEpsilon_B",
    "AATS1i",
    "ATS3dv",
    "VR2_Dzpe",
    "SpDiam_Dzi",
    "ATSC1pe",
    "ATSC1m",
    "MW",
    "MACCS_FP_102",
    "AATSC5are",
    "ATSC0dv",
    "BCUTi-1l",
    "AMID_X",
    "SlogP_VSA2",
    "MACCS_FP_39",
    "VE3_Dzare",
    "AATSC2s",
    "EState_VSA8",
    "MACCS_FP_157",
    "VE3_A",
    "SdO",
    "PEOE_VSA12",
    "ATSC0p",
    "MID_X",
    "EState_VSA6",
    "ATS5are",
    "ATS4d",
    "EState_VSA9",
    "AATS3i",
    "MACCS_FP_3",
    "PEOEVSA9",
    "GATS2v",
    "ATSC0pe",
    "SpDiam_Dzse",
    "SpAbs_Dzp",
    "BCUTv-1l",
    "ATS4are",
    "MACCS_FP_49",
    "MACCS_FP_40",
    "MAXddsN",
    "PEOEVSA13",
    "VE1_Dzse",
    "VE2_Dzi",
    "SpMax_Dzi",
    "JGI3",
    "n5Ring",
    "slogPVSA3",
    "ZMIC4",
    "AATS3se",
    "ATS0dv",
    "SM1_Dzare",
    "ATSC1are",
    "ATSC1Z",
    "EstateVSA5",
    "AATS1s",
    "SpDiam_Dzare",
    "VSA_EState2",
    "MACCS_FP_96",
    "SM1_Dzv",
    "VR2_D",
    "VE2_Dzv",
    "SdssC",
    "AATSC5s",
    "SpAbs_Dzpe",
    "ETA_shape_y",
    "AATSC5se",
    "MolWt",
    "AATS0i",
    "GATS2i",
    "PEOEVSA11",
    "AETA_eta_R",
    "SM1_Dzp",
    "VE1_Dzpe",
    "BCUTs-1l",
    "MACCS_FP_69",
    "SpDiam_Dzpe",
    "MATS2v",
    "AATSC1s",
    "MATS1v",
    "VSAEstate1",
    "ATS1v",
    "MATS1se",
    "AATS5s",
    "ATS1Z",
    "SlogP_VSA4",
    "SpAbs_Dzi",
    "AATSC3are",
    "SpMax_Dzse",
    "nAtom",
    "ATSC0are",
    "ATS5d",
    "AATS1v",
    "MATS1c",
    "BCUTare-1l",
    "VE2_Dzp",
    "SpAbs_Dzare",
    "CIC1",
    "Mare",
    "GATS2se",
    "MINddsN",
    "C1SP3",
    "AATS3d",
    "MACCS_FP_132",
    "MINaaCH",
    "ATS7i",
    "MACCS_FP_85",
    "GATS5se",
    "AATSC3d",
    "MINdO",
    "TpiPC10",
    "GATS2are",
    "VE1_Dzi",
    "AMID_C",
    "AATS1dv",
    "SaaN",
    "MINsssN",
    "AATS1d",
    "EstateVSA7",
    "MACCS_FP_67",
    "ETA_beta_s",
    "Mi",
    "HybRatio",
    "BCUTse-1l",
    "MATS5se",
    "AATS0are",
    "ATSC3v",
    "ATSC4dv",
    "nBondsD",
    "nBondsKS",
    "ATS6i",
    "SpAD_Dzare",
    "ATS2v",
    "NdssC",
    "slogPVSA2",
    "SpDiam_Dzp",
    "VE2_DzZ",
    "EstateVSA1",
    "SpMax_Dzare",
    "GATS2Z",
    "MACCS_FP_86",
    "BIC2",
    "VE3_D",
    "AATS7m",
    "MACCS_FP_119",
    "MACCS_FP_61",
    "MACCS_FP_153",
    "GATS2m",
    "GATS2s",
    "Si",
    "PEOEVSA1",
    "MATS5are",
    "MATS1pe",
    "ATS6are",
    "SMR_VSA4",
    "SlogP_VSA3",
    "SpMax_Dzv",
    "EState_VSA2",
    "LogEE_Dzi",
    "VE2_Dzse",
    "VE3_DzZ",
    "SpAD_Dzse",
    "MAXtN",
    "AATSC2se",
    "ETA_beta_ns",
    "GATS3d",
    "Sm",
    "GATS5pe",
    "ATS6se",
    "ATSC1i",
    "MAXdO",
    "MRVSA3",
    "GATS5dv",
    "MAXsssN",
    "MATS3d",
    "ATS6pe",
    "PEOE_VSA2",
    "AATS0dv",
    "SpAbs_Dzse",
    "VE1_Dzv",
    "MINssCH2",
    "AATS2dv",
    "ATS1dv",
    "CIC2",
    "SpMax_Dzpe",
    "MACCS_FP_159",
    "ATS1m",
    "MATS2d",
    "MAXsCH3",
    "MAXaaCH",
    "AATS6i",
    "VE1_A",
    "MATS2c",
    "VE2_A",
    "LogEE_Dzare",
    "SRW08",
    "AXp-1d",
    "AATS0d",
    "MACCS_FP_95",
    "AATS1m",
    "VSA_EState8",
    "AATSC2v",
    "SpAD_Dzi",
    "SIC4",
    "MID_C",
    "AATSC1i",
    "AATS2v",
    "GATS2pe",
    "nBondsM",
    "GATS7d",
    "AATSC0d",
    "LogEE_Dzse",
    "SpMAD_D",
    "VE1_Dzm",
    "BIC4",
    "MWC09",
    "VE2_Dzm",
    "MIC1",
    "AATS2p",
    "MACCS_FP_60",
    "SMR_VSA6",
    "GATS4are",
    "VE1_D",
    "SlogP_VSA5",
    "MACCS_FP_111",
    "VE2_D",
    "Kier3",
    "MATS1d",
    "fMF",
    "ATSC1c",
    "AXp-6dv",
    "ATSC1v",
    "AATS7d",
    "Xch-7dv",
    "MATS5pe",
    "nS",
    "MATS2se",
    "GATS3are",
    "AXp-2dv",
    "MACCS_FP_88",
    "TIC1",
    "SMR_VSA1",
    "VE1_DzZ",
    "MATS6c",
    "AXp-5dv",
    "SpMAD_Dzm",
    "GATS3se",
    "SIC5",
    "IC1",
    "AATS0pe",
    "SpAD_Dzpe",
    "AATS2are",
    "MATS4d",
    "MATS4s",
    "ATS3m",
    "ATSC4s",
    "AETA_eta_F",
    "MRVSA5",
    "AATSC2i",
    "GATS3pe",
    "Mpe",
    "MWC10",
    "Kier2",
    "ATSC2i",
    "SpMAD_DzZ",
    "StsC",
    "BIC5",
    "piPC2",
    "GATS3Z",
    "AATS2se",
    "ATS7pe",
    "GATS1d",
    "MACCS_FP_158",
    "GATS5are",
    "MRVSA0",
    "n6aHRing",
    "AATS2s",
    "SpAD_Dzv",
    "TIC2",
    "SRW10",
    "ATS5p",
    "BCUTpe-1l",
    "PEOEVSA2",
    "Sare",
    "ATSC4se",
    "MWC06",
    "VSA_EState6",
    "SpDiam_Dzv",
    "MACCS_FP_160",
    "MDEO-12",
    "MATS1are",
    "GATS4s",
    "MWC08",
    "MACCS_FP_142",
    "MIC5",
    "VSAEstate5",
    "MACCS_FP_110",
    "MATS3Z",
    "GATS1i",
    "GATS4d",
    "ATS7se",
    "ATS4p",
    "SRW06",
    "AATS1Z",
    "MDEO-11",
    "slogPVSA4",
    "ATS2m",
    "MACCS_FP_97",
    "AATSC6dv",
    "LogEE_Dzpe",
    "ATSC0i",
    "ATS7are",
    "AATS4se",
    "BCUTZ-1l",
    "SIC1",
    "ATS6d",
    "ATS4dv",
    "ETA_dEpsilon_A",
    "SpAbs_Dzv",
    "GATS3m",
    "MATS3m",
    "Sse",
    "SRW05",
    "CIC5",
    "MACCS_FP_44",
    "VR1_D",
    "VSAEstate7",
    "GATS2dv",
    "AATS4pe",
    "ETA_beta",
    "Xp-2d",
    "ATSC2se",
    "LogEE_DzZ",
    "piPC1",
    "IC2",
    "PEOEVSA7",
    "AATS4v",
    "GATS3c",
    "SpMax_Dzm",
    "MACCS_FP_139",
    "VE1_Dzp",
    "VR1_Dzm",
    "CIC4",
    "VE2_Dzare",
    "ATSC2dv",
    "ATS0d",
    "GATS5c",
    "nARing",
    "TMWC10",
    "MIC2",
    "PEOE_VSA9",
    "AATS4m",
    "LogEE_Dzv",
    "ATSC2v",
    "AATSC6p",
    "VR2_A",
    "AATS5v",
    "PEOE_VSA3",
    "AATS5se",
    "ATS6p",
    "Mp",
    "AATSC3dv",
    "AATSC6c",
    "AATSC4se",
    "AXp-3dv",
    "AATS0p",
    "MDEC-22",
    "MIC4",
    "AATS4Z",
    "AATSC2dv",
    "ETA_shape_p",
    "PEOE_VSA8",
    "VSA_EState1",
    "ATSC2c",
    "BCUTm-1l",
    "GATS2p",
    "ATSC4d",
    "MAXsOH",
    "AATSC0m",
    "SpDiam_DzZ",
    "ETA_eta_RL",
    "JGI1",
    "VR3_DzZ",
    "MAXssCH2",
    "MATS2m",
    "AMW",
    "ATSC4pe",
    "AATSC0Z",
    "ETA_epsilon_1",
    "bpol",
    "AATS5are",
    "MATS2dv",
    "VSA_EState7",
    "AATSC2pe",
    "nBonds",
    "AATS4are",
    "SpMax_DzZ",
    "ATS1i",
    "ATSC2pe",
    "PEOE_VSA5",
    "MIC3",
    "PEOEVSA4",
    "SpAD_DzZ",
    "AATSC4dv",
    "ETA_eta_FL",
    "VSAEstate4",
    "MACCS_FP_65",
    "ATS2Z",
    "Spe",
    "ATSC2d",
    "MINsCH3",
    "AATSC2d",
    "MACCS_FP_114",
    "Mm",
    "SpAbs_DzZ",
    "AATSC0v",
    "AATSC4d",
    "PEOEVSA8",
    "ATSC0d",
    "ATSC2are",
    "SaasC",
    "SpAbs_Dzm",
    "MATS6p",
    "MATS3pe",
    "SpDiam_Dzm",
    "VR1_Dzse",
    "AETA_eta_BR",
    "VSAEstate6",
    "mZagreb1",
    "MWC07",
    "AATS0m",
    "AATSC0p",
    "PetitjeanIndex",
    "AATSC2are",
    "AETA_beta_ns_d",
    "LogEE_Dzm",
    "AATS2pe",
    "IC3",
    "MZ",
    "AATS0Z",
    "GATS5d",
    "PEOE_VSA7",
    "GATS3dv",
    "MATS6se",
    "IC5",
    "Kier1",
    "MACCS_FP_51",
    "MATS2are",
    "MWC04",
    "GATS2d",
    "MID",
    "AATS3m",
    "EState_VSA1",
    "VSAEstate8",
    "MACCS_FP_12",
    "VSAEstate0",
    "MACCS_FP_92",
    "VSA_EState5",
    "ATS3s",
    "AXp-1dv",
    "EState_VSA4",
    "PEOEVSA6",
    "MATS3v",
    "ATS4pe",
    "GATS3p",
    "AATSC3v",
    "Mv",
    "ATS0m",
    "ATSC4are",
    "ATS2dv",
    "SpAD_Dzm",
    "MPC4",
    "MACCS_FP_82",
    "ATSC0m",
    "EstateVSA0",
    "SpAbs_A",
    "AETA_eta_B",
    "AXp-4d",
    "ATS3are",
    "EstateVSA3",
    "MATS2i",
    "MACCS_FP_72",
    "piPC5",
    "MACCS_FP_109",
    "VR1_Dzp",
    "VR1_Dzare",
    "AATS5p",
    "ATS6v",
    "JGI5",
    "NdS",
    "GATS4i",
    "ATS0Z",
    "MACCS_FP_146",
    "nBondsKD",
    "ATS0s",
    "nAcid",
    "AATS7s",
    "VR3_Dzv",
    "MATS2p",
    "ATS2are",
    "MATS2pe",
    "ATS7d",
    "SRW04",
    "JGT10",
    "SdS",
    "GATS3s",
    "AATSC4are",
    "ETA_dAlpha_A",
    "ATSC3p",
    "VSA_EState9",
    "GATS4se",
    "AATS5pe",
    "LogEE_D",
    "AATSC6v",
    "BalabanJ",
    "MINsOH",
    "MINsF",
    "ATSC0Z",
    "ATS0se",
    "ATSC2s",
    "AATS4d",
    "AATS5d",
    "MATS4c",
    "SsCH3",
    "ATS2se",
    "nBondsS",
    "MATS3c",
    "ATS0are",
    "AXp-3d",
    "ATS2s",
    "MACCS_FP_93",
    "MATS3p",
    "AATSC3m",
    "MATS6v",
    "MATS3are",
    "ATS0pe",
    "GATS4c",
    "ATSC3se",
    "ATS5s",
    "AATS2Z",
    "MATS6m",
    "AATSC2m",
    "MATS3dv",
    "GATS1v",
    "AXp-2d",
    "Diameter",
    "AATSC5m",
    "AATSC3Z",
    "ATS3p",
    "MATS2Z",
    "MWC02",
    "ATSC1d",
    "MWC05",
    "IC4",
    "ATSC3m",
    "AATS0v",
    "ATS2i",
    "MATS4Z",
    "GATS6s",
    "ATS5v",
    "MATS6Z",
    "AATS5m",
    "MATS4i",
    "Xp-3dv",
    "AATS5Z",
    "AATSC4v",
    "ATS2pe",
    "ATSC5dv",
    "MRVSA4",
    "MACCS_FP_77",
    "GATS6p",
    "AATS3are",
    "SssO",
    "ETA_eta_B",
    "MPC2",
    "AATSC2p",
    "MATS4are",
    "ATSC3Z",
    "VR1_Dzv",
    "ATSC3s",
    "NaasN",
    "VR1_Dzi",
    "ATS7p",
    "MAXsF",
    "NsCH3",
    "ATS3v",
    "RotRatio",
    "MATS4se",
    "MATS4v",
    "ATSC5d",
    "nBase",
    "ATSC2m",
    "MATS4dv",
    "ATS1se",
    "TopoShapeIndex",
    "ATS1are",
    "MATS5c",
    "AATSC1d",
    "EstateVSA4",
    "AATSC2Z",
    "ETA_eta_R",
    "BertzCT",
    "ATS7v",
    "ATSC4m",
    "RotatableBonds",
    "GGI3",
    "AXp-0d",
    "TIC3",
    "ATSC4c",
    "ETA_eta_BR",
    "GATS6se",
    "GATS4v",
    "Xch-5d",
    "VE2_Dzpe",
    "SMR_VSA5",
    "ATS3i",
    "ATSC2Z",
    "MATS4p",
    "AATSC4Z",
    "GATS6v",
    "ATSC3pe",
    "MACCS_FP_54",
    "ATS6s",
    "MATS4m",
    "MACCS_FP_56",
    "PEOEVSA10",
    "GATS3v",
    "MATS5v",
    "NddssS",
    "MATS3i",
    "MAXssO",
    "AATSC5Z",
    "PEOE_VSA13",
    "AATS3pe",
    "AATS4i",
    "GATS4dv",
    "naHRing",
    "ETA_dPsi_B",
    "nC",
    "PEOEVSA12",
    "Xp-0d",
    "PEOE_VSA11",
    "ATSC2p",
    "SlogP_VSA10",
    "GATS4pe",
    "AATSC4c",
    "GATS4Z",
    "MATS6pe",
    "Xch-6dv",
    "AATS2m",
    "Xpc-5d",
    "Zagreb2",
    "VR3_Dzm",
    "AXp-4dv",
    "ATSC4v",
    "ATSC3are",
    "AXp-5d",
    "GATS6pe",
    "GATS6i",
    "MACCS_FP_24",
    "NdssS",
    "TIC4",
    "MINssO",
    "MDEC-12",
    "VR1_Dzpe",
    "MWC03",
    "AATS4p",
    "AATSC3p",
    "GATS3i",
    "nBondsT",
    "SM1_A",
    "piPC4",
    "MACCS_FP_120",
    "MATS6dv",
    "VR3_Dzi",
    "MDEC-23",
    "MATS6are",
    "VR1_DzZ",
    "AATSC4pe",
    "ATSC3dv",
    "C1SP1",
    "MATS2s",
    "GATS6are",
    "MATS4pe",
    "AATSC6pe",
    "MACCS_FP_138",
    "VSAEstate3",
    "ATS3pe",
    "slogPVSA9",
    "GATS4m",
    "Zagreb1",
    "ATSC4Z",
    "AATS3Z",
    "AATSC6se",
    "ATS3se",
    "MACCS_FP_16",
    "ATS6m",
    "ATSC5s",
    "NtsC",
    "AATSC4m",
    "GATS4p",
    "AATSC5c",
    "Xc-3d",
    "Xp-4d",
    "ATSC5are",
    "SpDiam_D",
    "NssO",
    "ECIndex",
    "Xc-3dv",
    "ATS1pe",
    "JGI2",
    "SM1_D",
    "GGI1",
    "nRot",
    "VR3_Dzp",
    "ATS1d",
    "MACCS_FP_98",
    "ATS3Z",
    "MPC3",
    "ATS2d",
    "AATSC6are",
    "GATS5v",
    "VR3_Dzare",
    "AATS5i",
    "MINdssS",
    "MAXdssS",
    "n3AHRing",
    "EState_VSA3",
    "GGI5",
    "Xpc-4d",
    "ATSC3i",
    "AATS6p",
    "SpAD_D",
    "AATSC5i",
    "ATSC3c",
    "ATS5m",
    "Xp-6d",
    "AATSC8c",
    "fragCpx",
    "MATS5i",
    "ATS4v",
    "AXp-7dv",
    "TMPC10",
    "SsssCH",
    "ATS3d",
    "VR3_Dzpe",
    "SpAbs_D",
    "AATSC3i",
    "MDEC-13",
    "ATS5Z",
    "GATS6c",
    "MDEC-11",
    "VR3_Dzse",
    "VSA_EState4",
    "ATS7s",
    "ATSC5Z",
    "AATSC4i",
    "AATSC6m",
    "ATS6dv",
    "MATS8c",
    "MACCS_FP_155",
    "ATSC4i",
    "ATSC6s",
    "EstateVSA2",
    "EState_VSA5",
    "ATSC5v",
    "Xp-1d",
    "n3HRing",
    "SdsCH",
    "Xpc-4dv",
    "MACCS_FP_147",
    "TIC5",
    "MACCS_FP_13",
    "n3ARing",
    "AATS5dv",
    "Xp-3d",
    "NssCH2",
    "MPC5",
    "ATSC5c",
    "ATSC6Z",
    "GATS5p",
    "ATS4Z",
    "ATS8pe",
    "AATSC6Z",
    "GGI2",
    "MACCS_FP_115",
    "mZagreb2",
    "n3Ring",
    "ATS5dv",
    "AATS6d",
    "ATSC5pe",
    "Xch-4d",
    "JGI4",
    "SaasN",
    "AATS6s",
    "ATS6Z",
    "TIC0",
    "ATSC8c",
    "AXp-6d",
    "AATSC5p",
    "ATS7Z",
    "Xch-4dv",
    "ATSC5m",
    "NaaCH",
    "AATS7are",
    "MACCS_FP_108",
    "n6HRing",
    "SMR_VSA9",
    "ATS8i",
    "VR3_D",
    "Xch-3d",
    "AATSC4p",
    "AATS6Z",
    "GATS7c",
    "AATS7Z",
    "EState_VSA7",
    "GATS6dv",
    "GGI4",
    "AATS6m",
    "GATS6m",
    "Xp-5dv",
    "VR3_A",
    "GATS6d",
    "MACCS_FP_22",
    "nRing",
    "MATS5p",
    "piPC7",
    "ATSC5se",
    "SpAD_A",
    "MACCS_FP_118",
    "MACCS_FP_112",
    "ATSC6se",
    "ATSC4p",
    "ATSC7c",
    "SsNH2",
    "MRVSA6",
    "ATSC6c",
    "MWC01",
    "Xch-3dv",
    "AATS7pe",
    "GATS8i",
    "ATSC5p",
    "AATS7i",
    "Xp-5d",
    "nBondsO",
    "nHeavyAtom",
    "SpMax_D",
    "ATSC5i",
    "ATSC6dv",
    "AATS6v",
    "AATS6pe",
    "AATSC5v",
    "MACCS_FP_133",
    "AATS7se",
    "GATS7se",
    "SRW03",
    "ATSC6m",
    "MACCS_FP_75",
    "MACCS_FP_84",
    "ATSC8se",
    "GATS5i",
    "Radius",
    "AATS7v",
    "SlogP_VSA6",
    "WPol",
    "Xpc-6dv",
    "MACCS_FP_149",
    "ATSC6pe",
    "AATS6are",
    "MATS8are",
    "ATS8are",
    "n6aRing",
    "MAXsssCH",
    "Xp-6dv",
    "MACCS_FP_15",
    "Xp-7d",
    "n6Ring",
    "SdssS",
    "SMR_VSA7",
    "EstateVSA6",
    "AATSC7v",
    "ATSC7d",
    "MDEC-33",
    "AATS6se",
    "GATS6Z",
    "MACCS_FP_104",
    "WPath",
    "ETA_shape_x",
    "MRVSA8",
    "MACCS_FP_140",
    "C3SP2",
    "GATS8c",
    "ATS4m",
    "ATSC6i",
    "AATS6dv",
    "Xp-4dv",
    "ATS8p",
    "SssCH2",
    "Xpc-5dv",
    "ATSC6are",
    "MINsssCH",
    "MATS7d",
    "VR1_A",
    "C4SP3",
    "Xpc-6d",
    "C2SP2",
    "JGI6",
    "GATS8p",
    "MACCS_FP_63",
    "AATSC7s",
    "AATSC8s",
    "GATS7pe",
    "MINsCl",
    "AATSC7d",
    "GATS7dv",
    "ATS8d",
    "ATSC7p",
    "GATS8s",
    "MACCS_FP_71",
    "MACCS_FP_90",
    "ATSC6v",
    "piPC6",
    "MACCS_FP_165",
    "AATSC7c",
    "AATSC7pe",
    "ETA_beta_ns_d",
    "SssssC",
    "MACCS_FP_129",
    "MATS7p",
    "ATS8se",
    "AATS8dv",
    "MACCS_FP_48",
    "C2SP3",
    "MACCS_FP_135",
    "SRW02",
    "ATSC6d",
    "MATS7s",
    "MACCS_FP_53",
    "MATS8s",
    "MATS8se",
    "MATS7v",
    "MATS7c",
    "AATSC7Z",
    "SddssS",
    "ATSC6p",
    "AATS7p",
    "NsssCH",
    "AATS8p",
    "AXp-7d",
    "GATS8se",
    "ATSC7Z",
    "MACCS_FP_103",
    "MACCS_FP_87",
    "ATSC8p",
    "MACCS_FP_42",
    "GATS7are",
    "nCl",
    "MATS7m",
    "MATS7se",
    "ATSC7s",
    "MATS8dv",
    "AATSC8d",
    "AATSC8p",
    "NddsN",
    "AATSC7i",
    "MACCS_FP_163",
    "SdsssP",
    "GATS7m",
    "MACCS_FP_94",
    "MATS7pe",
    "MAXsCl",
    "GATS8pe",
    "VAdjMat",
    "slogPVSA5",
    "AATSC8are",
    "MPC7",
    "GATS7p",
    "GATS8dv",
    "GATS8are",
    "MATS7are",
    "Xc-5d",
    "MATS7i",
    "MPC8",
    "AATSC8i",
    "ATS8s",
    "SsCl",
    "ATSC8s",
    "ATSC8dv",
    "ATSC8m",
    "MATS8p",
    "GATS7Z",
    "NssssC",
    "MACCS_FP_128",
    "NdsCH",
    "ATSC8v",
    "NsCl",
    "SddsN",
    "MDEN-33",
    "ATSC8are",
    "AATSC8se",
    "AATS8m",
    "AATSC7se",
    "GATS8v",
    "MACCS_FP_116",
    "Xch-5dv",
    "MATS7Z",
    "MACCS_FP_79",
    "AATS8i",
    "MATS7dv",
    "ATS7m",
    "AATS8are",
    "piPC8",
    "NdsssP",
    "MATS8i",
    "ATS8v",
    "SaaO",
    "MACCS_FP_74",
    "MACCS_FP_91",
    "ATSC7m",
    "Xp-7dv",
    "AATS8Z",
    "ATSC7are",
    "ATSC7i",
    "AATS8v",
    "MACCS_FP_136",
    "MACCS_FP_58",
    "NaasC",
    "AATS8s",
    "MINaaO",
    "ATSC7v",
    "MAXaaO",
    "AATSC7dv",
    "ATSC8d",
    "GATS7i",
    "ATSC8Z",
    "ATSC7pe",
    "MACCS_FP_55",
    "MACCS_FP_100",
    "MDEN-11",
    "AATSC7are",
    "AATSC7m",
    "JGI7",
    "MPC6",
    "SaaCH",
    "GATS7v",
    "MDEO-22",
    "GATS7s",
    "SssS",
    "MDEC-34",
    "AATS8se",
    "MATS8v",
    "NsNH2",
    "MAXddssS",
    "AATSC7p",
    "nP",
    "MACCS_FP_29",
    "MATS8d",
    "MDEC-24",
    "n9FARing",
    "MACCS_FP_70",
    "Xc-5dv",
    "MATS8Z",
    "MATS8m",
    "GATS8d",
    "Xc-4dv",
    "nF",
    "MAXdsssP",
    "MACCS_FP_14",
    "NdNH",
    "n9FAHRing",
    "AATSC8dv",
    "NssS",
    "ATSC7se",
    "AATSC8pe",
    "GGI6",
    "MACCS_FP_144",
    "MACCS_FP_141",
    "MINdsN",
    "MATS8pe",
    "AATSC8Z",
    "MINdsssP",
    "nAromAtom",
    "AATSC8v",
    "n6ARing",
    "n9FHRing",
    "MAXssssC",
    "n9FRing",
    "SdNH",
    "nBondsA",
    "ATS8Z",
    "MACCS_FP_50",
    "GATS8Z",
    "AATS8pe",
    "ATS8m",
    "GGI7",
    "ATSC7dv",
    "nFHRing",
    "Xc-4d",
    "AATSC8m",
    "ATSC8pe",
    "ATS7dv",
    "MACCS_FP_23",
    "ATSC8i",
    "MINssssC",
    "SsF",
    "slogPVSA6",
    "GATS8m",
    "naRing",
    "MACCS_FP_162",
    "AATS8d",
    "NaaO",
    "MAXdsN",
    "SlogP_VSA7",
    "MACCS_FP_25",
    "MACCS_FP_150",
    "MINddC",
    "MAXsBr",
    "MDEC-14",
    "MDEN-13",
    "SsBr",
    "MPC9",
    "MACCS_FP_99",
    "C3SP3",
    "MACCS_FP_52",
    "SddC",
    "MACCS_FP_66",
    "nAromBond",
    "ATS8dv",
    "piPC9",
    "JGI9",
    "MACCS_FP_76",
    "slogPVSA10",
    "NsBr",
    "JGI8",
    "MAXddC",
    "MACCS_FP_46",
    "MACCS_FP_101",
    "nFAHRing",
    "n10FHRing",
    "NddC",
    "NsF",
    "MACCS_FP_34",
    "Xc-6d",
    "MINdCH2",
    "MINsBr",
    "MACCS_FP_113",
    "n10FaHRing",
    "MACCS_FP_31",
    "JGI10",
    "SdCH2",
    "SlogP_VSA11",
    "n5aHRing",
    "SssssSn",
    "GhoseFilter",
    "MACCS_FP_20",
    "piPC10",
    "nBr",
    "MAXssssSn",
    "MACCS_FP_37",
    "MAXdCH2",
    "GGI8",
    "MPC10",
    "NsI",
    "n5aRing",
    "GGI9",
    "MAXsSH",
    "MINssssSn",
    "NdCH2",
    "Xc-6dv",
    "GGI10",
    "nFaHRing",
    "MACCS_FP_27",
    "n6AHRing",
    "NsSH",
    "Lipinski",
    "MINssS",
    "NssNH",
    "NssssSn",
    "MAXssS",
    "nI",
    "SlogP_VSA8",
    "slogPVSA7",
    "SsSH",
    "NssssGe",
    "MDEC-44",
    "MACCS_FP_10",
    "MACCS_FP_81",
    "MACCS_FP_30",
    "nFRing",
    "MINsI",
    "SssNH",
    "nFARing",
    "NssssSi",
    "MACCS_FP_35",
    "SsI",
    "MACCS_FP_105",
    "MINddssS",
    "MINsSH",
    "MACCS_FP_5",
    "MAXsI",
    "MACCS_FP_36",
    "SssssSi",
    "NtCH",
    "MACCS_FP_166",
    "SssssGe",
    "MACCS_FP_145",
    "nFaRing",
    "MACCS_FP_17",
    "MAXaaaC",
    "MINssssSi",
    "NsssB",
    "MACCS_FP_125",
    "MACCS_FP_28",
    "MAXtCH",
    "StCH",
    "MINaaaC",
    "C2SP1",
    "n10FRing",
    "MAXssssSi",
    "n10FaRing",
    "SaaaC",
    "MACCS_FP_21",
    "MINtCH",
    "SsssP",
    "NaaaC",
    "MINssssGe",
    "NsssP",
    "n7FRing",
    "nBridgehead",
    "MACCS_FP_19",
    "SaaS",
    "n7FARing",
    "MACCS_FP_18",
    "nB",
    "nG12FaRing",
    "nG12FHRing",
    "MAXssssGe",
    "MACCS_FP_68",
    "nG12FRing",
    "n11FRing",
    "n4Ring",
    "MACCS_FP_64",
    "n10FARing",
    "n8Ring",
    "nG12FaHRing",
    "MACCS_FP_59",
    "n4ARing",
    "SaaNH",
    "MACCS_FP_11",
    "n8ARing",
    "n10AHRing",
    "n7ARing",
    "n7Ring",
    "nG12FARing",
    "n10Ring",
    "SsssB",
    "NaaS",
    "n10HRing",
    "nSpiro",
    "n10ARing",
    "NaaNH",
    "n11FARing",
    "n12FARing",
    "n6FARing",
    "n6FRing",
    "EstateVSA10",
    "MACCS_FP_0",
    "MACCS_FP_1",
    "MACCS_FP_2",
    "MACCS_FP_26",
    "MACCS_FP_32",
    "MACCS_FP_33",
    "MACCS_FP_38",
    "MACCS_FP_4",
    "MACCS_FP_43",
    "MACCS_FP_45",
    "MACCS_FP_6",
    "MACCS_FP_62",
    "MACCS_FP_7",
    "MACCS_FP_8",
    "MACCS_FP_80",
    "MACCS_FP_9",
    "MAXaaNH",
    "MAXaaS",
    "MAXaasN",
    "MAXdNH",
    "MAXdssSe",
    "MAXsssB",
    "MAXsssP",
    "MDEN-22",
    "MDEN-23",
    "MINaaNH",
    "MINaaS",
    "MINaasN",
    "MINdNH",
    "MINdssSe",
    "MINsssB",
    "MINsssP",
    "MRVSA7",
    "NaaSe",
    "NdSe",
    "NddssSe",
    "NsAsH2",
    "NsGeH3",
    "NsLi",
    "NsNH3",
    "NsPH2",
    "NsPbH3",
    "NsSeH",
    "NsSiH3",
    "NsSnH3",
    "NssAsH",
    "NssBH",
    "NssBe",
    "NssGeH2",
    "NssNH2",
    "NssPH",
    "NssPbH2",
    "NssSe",
    "NssSiH2",
    "NssSnH2",
    "NsssAs",
    "NsssGeH",
    "NsssNH",
    "NsssPbH",
    "NsssSiH",
    "NsssSnH",
    "NsssdAs",
    "NssssB",
    "NssssBe",
    "NssssN",
    "NssssPb",
    "NsssssAs",
    "NsssssP",
    "SMR_VSA8",
    "SaaSe",
    "SdSe",
    "SddssSe",
    "SlogP_VSA9",
    "SsAsH2",
    "SsGeH3",
    "SsLi",
    "SsNH3",
    "SsPH2",
    "SsPbH3",
    "SsSeH",
    "SsSiH3",
    "SsSnH3",
    "SssAsH",
    "SssBH",
    "SssBe",
    "SssGeH2",
    "SssNH2",
    "SssPH",
    "SssPbH2",
    "SssSe",
    "SssSiH2",
    "SssSnH2",
    "SsssAs",
    "SsssGeH",
    "SsssNH",
    "SsssPbH",
    "SsssSiH",
    "SsssSnH",
    "SsssdAs",
    "SssssB",
    "SssssBe",
    "SssssN",
    "SssssPb",
    "SsssssAs",
    "SsssssP",
    "n10FAHRing",
    "n10aHRing",
    "n10aRing",
    "n11AHRing",
    "n11ARing",
    "n11FAHRing",
    "n11FHRing",
    "n11FaHRing",
    "n11FaRing",
    "n11HRing",
    "n11Ring",
    "n11aHRing",
    "n11aRing",
    "n12AHRing",
    "n12ARing",
    "n12FAHRing",
    "n12FHRing",
    "n12FRing",
    "n12FaHRing",
    "n12FaRing",
    "n12HRing",
    "n12Ring",
    "n12aHRing",
    "n12aRing",
    "n3aHRing",
    "n3aRing",
    "n4AHRing",
    "n4FAHRing",
    "n4FARing",
    "n4FHRing",
    "n4FRing",
    "n4FaHRing",
    "n4FaRing",
    "n4HRing",
    "n4aHRing",
    "n4aRing",
    "n5FAHRing",
    "n5FARing",
    "n5FHRing",
    "n5FRing",
    "n5FaHRing",
    "n5FaRing",
    "n6FAHRing",
    "n6FHRing",
    "n6FaHRing",
    "n6FaRing",
    "n7AHRing",
    "n7FAHRing",
    "n7FHRing",
    "n7FaHRing",
    "n7FaRing",
    "n7HRing",
    "n7aHRing",
    "n7aRing",
    "n8AHRing",
    "n8FAHRing",
    "n8FARing",
    "n8FHRing",
    "n8FRing",
    "n8FaHRing",
    "n8FaRing",
    "n8HRing",
    "n8aHRing",
    "n8aRing",
    "n9AHRing",
    "n9ARing",
    "n9FaHRing",
    "n9FaRing",
    "n9HRing",
    "n9Ring",
    "n9aHRing",
    "n9aRing",
    "nG12AHRing",
    "nG12ARing",
    "nG12FAHRing",
    "nG12HRing",
    "nG12Ring",
    "nG12aHRing",
    "nG12aRing",
    "slogPVSA8",
]
five_fold_pi = all_features[:50]

# =======================================================
# 3. ANN Model
# =======================================================
def build_ann_model(input_dim):
    model = Sequential()
    model.add(Dense(256, activation=tf.keras.layers.LeakyReLU(alpha=0.1), input_dim=input_dim))
    model.add(Dropout(0.1))
    model.add(Dense(64, activation=tf.keras.layers.LeakyReLU(alpha=0.1), input_dim=input_dim))
    model.add(Dropout(0.1))
    model.add(Dense(32, activation=tf.keras.layers.LeakyReLU(alpha=0.1), input_dim=input_dim))
    model.add(Dropout(0.1))
    model.add(Dense(16, activation=tf.keras.layers.LeakyReLU(alpha=0.1)))
    model.add(Dropout(0.1))
    model.add(LeakyReLU(alpha=0.1))
    model.add(Dense(1, activation="linear"))
    model.compile(optimizer='adam', loss='mse')
    return model

# =======================================================
# 4. Data load
# =======================================================
train_df = pd.read_csv(train_csv_path)
test_df  = pd.read_csv(test_csv_path)

y_train = train_df[target_col]
X_train = train_df.drop(columns=drop_cols)

y_test  = test_df[target_col]
X_test  = test_df.drop(columns=drop_cols)

print("X_train shape (raw):", X_train.shape)
print("y_train shape:", y_train.shape)
print("X_test shape (raw):", X_test.shape)
print("y_test shape:", y_test.shape)

# =======================================================
# 5. Apply your feature selection list (five_fold_pi)
# =======================================================
# Train/Test'te bulunmayan feature'ları güvenli şekilde ele
train_cols = set(X_train.columns)
test_cols  = set(X_test.columns)

selected_present = [c for c in five_fold_pi if (c in train_cols and c in test_cols)]
missing_in_train = [c for c in five_fold_pi if c not in train_cols]
missing_in_test  = [c for c in five_fold_pi if c not in test_cols]

print(f"[Feature] Requested features: {len(five_fold_pi)}")
print(f"[Feature] Present in BOTH train & test: {len(selected_present)}")

if missing_in_train:
    print(f"[Warning] Missing in TRAIN (will skip): {len(missing_in_train)}")
    # print(missing_in_train)  # istersen aç
if missing_in_test:
    print(f"[Warning] Missing in TEST (will skip): {len(missing_in_test)}")
    # print(missing_in_test)

if len(selected_present) == 0:
    raise ValueError("None of the requested features exist in both train and test.")

X_train = X_train[selected_present].copy()
X_test  = X_test[selected_present].copy()

# Sadece tamamen NaN olan kolonları drop et (train-based, güvenli)
all_nan_cols = X_train.columns[X_train.notna().sum() == 0].tolist()
if all_nan_cols:
    print(f"[Pre-processing] Dropping {len(all_nan_cols)} all-NaN features (train-based).")
    X_train = X_train.drop(columns=all_nan_cols)
    X_test  = X_test.drop(columns=all_nan_cols, errors="ignore")

print(f"[Final] X_train shape: {X_train.shape}")
print(f"[Final] X_test  shape: {X_test.shape}")

# =======================================================
# 6. 5-Fold CV: hold-out + external test scoring
# =======================================================
kf = KFold(n_splits=5, shuffle=True, random_state=SEED)

fold_holdout_r2 = []
fold_holdout_mae = []
fold_test_r2 = []
fold_test_mae = []

print("\n========================================")
print("Model: ANN_MLP_five_fold_pi")
print("========================================")

for fold_idx, (tr_idx, val_idx) in enumerate(kf.split(X_train, y_train), start=1):
    X_tr, X_val = X_train.iloc[tr_idx], X_train.iloc[val_idx]
    y_tr, y_val = y_train.iloc[tr_idx], y_train.iloc[val_idx]

    # Fold-based preprocessing (NO leakage)
    imputer = SimpleImputer(strategy="mean")
    scalerX = StandardScaler()
    scalerY = StandardScaler()

    X_tr_imp   = imputer.fit_transform(X_tr)
    X_val_imp  = imputer.transform(X_val)
    X_test_imp = imputer.transform(X_test)

    X_tr_sc   = scalerX.fit_transform(X_tr_imp)
    X_val_sc  = scalerX.transform(X_val_imp)
    X_test_sc = scalerX.transform(X_test_imp)

    y_tr_sc  = scalerY.fit_transform(y_tr.values.reshape(-1, 1))
    y_val_sc = scalerY.transform(y_val.values.reshape(-1, 1))

    model = build_ann_model(input_dim=X_tr_sc.shape[1])

    es = EarlyStopping(
        monitor="val_loss",
        patience=PATIENCE,
        restore_best_weights=True
    )

    model.fit(
        X_tr_sc, y_tr_sc,
        validation_data=(X_val_sc, y_val_sc),
        epochs=EPOCHS,
        batch_size=BATCH_SIZE,
        verbose=VERBOSE_FIT,
        callbacks=[es]
    )

    # Hold-out (fold validation)
    y_val_pred_sc = model.predict(X_val_sc, verbose=0)
    y_val_pred = scalerY.inverse_transform(y_val_pred_sc).ravel()

    r2_val = r2_score(y_val, y_val_pred)
    mae_val = mean_absolute_error(y_val, y_val_pred)

    # External test
    y_test_pred_sc = model.predict(X_test_sc, verbose=0)
    y_test_pred = scalerY.inverse_transform(y_test_pred_sc).ravel()

    r2_test = r2_score(y_test, y_test_pred)
    mae_test = mean_absolute_error(y_test, y_test_pred)

    fold_holdout_r2.append(r2_val)
    fold_holdout_mae.append(mae_val)
    fold_test_r2.append(r2_test)
    fold_test_mae.append(mae_test)

    print(
        f"Fold {fold_idx}: "
        f"Hold-out R2={r2_val:.4f}, MAE={mae_val:.4f} | "
        f"Test R2={r2_test:.4f}, MAE={mae_test:.4f}"
    )

# =======================================================
# 7. Fold summaries
# =======================================================
print("\n--- 5-Fold Özet (Hold-out) ---")
print(f"Mean Hold-out R2:  {np.mean(fold_holdout_r2):.4f} ± {np.std(fold_holdout_r2):.4f}")
print(f"Mean Hold-out MAE: {np.mean(fold_holdout_mae):.4f} ± {np.std(fold_holdout_mae):.4f}")

print("\n--- 5-Fold Özet (Test, fold modelleri) ---")
print(f"Mean Test R2:  {np.mean(fold_test_r2):.4f} ± {np.std(fold_test_r2):.4f}")
print(f"Mean Test MAE: {np.mean(fold_test_mae):.4f} ± {np.std(fold_test_mae):.4f}")

# =======================================================
# 8. Full train -> test (single final fit)
# =======================================================
imputer_full = SimpleImputer(strategy="mean")
scalerX_full = StandardScaler()
scalerY_full = StandardScaler()

X_train_imp = imputer_full.fit_transform(X_train)
X_test_imp  = imputer_full.transform(X_test)

X_train_sc = scalerX_full.fit_transform(X_train_imp)
X_test_sc  = scalerX_full.transform(X_test_imp)

y_train_sc = scalerY_full.fit_transform(y_train.values.reshape(-1, 1))

final_model = build_ann_model(input_dim=X_train_sc.shape[1])
es_full = EarlyStopping(monitor="loss", patience=PATIENCE, restore_best_weights=True)

final_model.fit(
    X_train_sc, y_train_sc,
    epochs=EPOCHS,
    batch_size=BATCH_SIZE,
    verbose=VERBOSE_FIT,
    callbacks=[es_full]
)

y_test_pred_sc = final_model.predict(X_test_sc, verbose=0)
y_test_pred = scalerY_full.inverse_transform(y_test_pred_sc).ravel()

print("\n--- Full Training -> Test Performansı ---")
print(f"Full-train Test R2:  {r2_score(y_test, y_test_pred):.4f}")
print(f"Full-train Test MAE: {mean_absolute_error(y_test, y_test_pred):.4f}")
